### ISSUE TITLE
返回需要加密

### ISSUE THREAD

**Issue by CavinHuang** [willin/tuling#1]
{code: 40007, text: '请按规定的要求进行加密' }

**Comment by willin** [comment]
无法复现，请提供示例代码

<img width="375" alt="wx20180510-093821 2x" src="https://user-images.githubusercontent.com/1890238/39847791-16be4f26-5436-11e8-899d-abd876210a70.png">


另外我看了一下，现在图灵机器人更新了2.0版本接口。 很惭愧，竟然完全看不懂这么奇怪设计的用意。。。不太好更新 sdk。

**Comment by CavinHuang** [comment]
```
var TULING = require( 'tuling' );

var tuling = new TULING( { key: 'd0ac2c9427844063917a91ab265dd427' } );

tuling.send( {
	userid: 1,
	info: '你好吗',
	loc: '南京市'
} ).then( function ( result ) {
	console.log( result );
} )
```
完全用的readme里的示例代码，难道是因为我的key是最近申请的问题？
![](https://raw.githubusercontent.com/CavinHuang/img-manger/master/img/%E5%B1%8F%E5%B9%95%E5%BF%AB%E7%85%A7%202018-05-12%20%E4%B8%8B%E5%8D%8810.16.46.png)

---
看了一遍2.0文档，完全没看到加密在哪。。。。迷醉的文档

**Comment by CavinHuang** [comment]
@willin 已明白，是在图灵的个人中心开启了密钥这个东西！

**Comment by willin** [comment]
feel free to reopen it
